#!/usr/bin/env sh
# Interactive bootstrap script for .env.local
#
# Supports:
# - OpenAI hosted API
# - OpenAI-compatible local backend (e.g. vLLM)
#
# Writes .env.local in the repository root with safe local defaults
# matching docker-compose.yml.

set -eu

output_file=".env.local"

print_header() {
    printf '%s\n' "============================================================"
    printf '%s\n' "  langgraph-checkpoint-neo4j .env.local bootstrap"
    printf '%s\n' "============================================================"
    printf '\n'
}

prompt_with_default() {
    prompt_text="$1"
    default_value="$2"

    if [ -n "$default_value" ]; then
        printf "%s [%s]: " "$prompt_text" "$default_value" >&2
    else
        printf "%s: " "$prompt_text" >&2
    fi

    read -r user_value

    if [ -n "$user_value" ]; then
        printf '%s' "$user_value"
    else
        printf '%s' "$default_value"
    fi
}

prompt_secret_with_default() {
    prompt_text="$1"
    default_value="$2"

    if [ -n "$default_value" ]; then
        printf "%s [%s]: " "$prompt_text" "$default_value" >&2
    else
        printf "%s: " "$prompt_text" >&2
    fi

    stty -echo
    read -r user_value
    stty echo
    printf '\n' >&2

    if [ -n "$user_value" ]; then
        printf '%s' "$user_value"
    else
        printf '%s' "$default_value"
    fi
}

confirm_overwrite() {
    if [ ! -f "$output_file" ]; then
        return 0
    fi

    printf "%s already exists. Overwrite? [y/N]: " "$output_file" >&2
    read -r overwrite_answer

    case "$overwrite_answer" in
    y | Y | yes | YES)
        return 0
        ;;
    *)
        printf '%s\n' "Aborted. Existing $output_file was left unchanged." >&2
        exit 1
        ;;
    esac
}

choose_backend() {
    printf '%s\n' "Choose your OpenAI-compatible backend:"
    printf '%s\n' "  1) OpenAI hosted API"
    printf '%s\n' "  2) Local vLLM / OpenAI-compatible server"
    printf '\n'

    while true; do
        printf '%s' "Selection [1]: " >&2
        read -r backend_choice

        case "$backend_choice" in
        "" | 1)
            printf '%s' "openai"
            return 0
            ;;
        2)
            printf '%s' "vllm"
            return 0
            ;;
        *)
            printf '%s\n' "Please enter 1 or 2." >&2
            ;;
        esac
    done
}

write_env_file() {
    backend="$1"
    openai_base_url="$2"
    openai_api_key="$3"
    openai_model="$4"
    anthropic_api_key="$5"
    anthropic_model="$6"
    neo4j_host="$7"
    neo4j_bolt_port="$8"
    neo4j_http_port="$9"
    neo4j_uri="${10}"
    neo4j_user="${11}"
    neo4j_password="${12}"
    thread_id="${13}"
    huggingfacehub_api_token="${14}"
    ministral_port="${15}"
    ministral_replicas="${16}"

    cat >"$output_file" <<EOF
# Generated by scripts/bootstrap-env-local.sh
# Backend: $backend

OPENAI_BASE_URL=$openai_base_url
OPENAI_API_KEY=$openai_api_key
OPENAI_MODEL=$openai_model

ANTHROPIC_API_KEY=$anthropic_api_key
ANTHROPIC_MODEL=$anthropic_model

NEO4J_HOST=$neo4j_host
NEO4J_BOLT_PORT=$neo4j_bolt_port
NEO4J_HTTP_PORT=$neo4j_http_port
NEO4J_URI=$neo4j_uri
NEO4J_USER=$neo4j_user
NEO4J_PASSWORD=$neo4j_password

THREAD_ID=$thread_id

HUGGINGFACEHUB_API_TOKEN=$huggingfacehub_api_token
MINISTRAL_PORT=$ministral_port
MINISTRAL_REPLICAS=$ministral_replicas
EOF
}

main() {
    print_header
    confirm_overwrite

    backend="$(choose_backend)"
    printf '\n'

    if [ "$backend" = "openai" ]; then
        openai_base_url="$(prompt_with_default "OpenAI base URL" "https://api.openai.com/v1")"
        openai_api_key="$(prompt_secret_with_default "OpenAI API key" "")"
        openai_model="$(prompt_with_default "OpenAI model" "gpt-4.1")"
        anthropic_api_key=""
        anthropic_model="claude-sonnet-4-5"
        huggingfacehub_api_token=""
        ministral_port="7374"
        ministral_replicas="0"
    else
        openai_base_url="$(prompt_with_default "vLLM base URL" "http://localhost:7374/v1")"
        openai_api_key="$(prompt_secret_with_default "OpenAI-compatible API key" "dummy")"
        openai_model="$(prompt_with_default "Served model name" "ministral-3b-instruct")"
        anthropic_api_key=""
        anthropic_model="claude-sonnet-4-5"
        huggingfacehub_api_token="$(prompt_secret_with_default "Hugging Face Hub token (for local vLLM pulls)" "")"
        ministral_port="$(prompt_with_default "Host port for ministral/vLLM" "7374")"
        ministral_replicas="$(prompt_with_default "MINISTRAL_REPLICAS" "1")"
    fi

    printf '\n'
    printf '%s\n' "Neo4j local defaults (matching docker-compose.yml):"

    neo4j_host="$(prompt_with_default "Neo4j host" "localhost")"
    neo4j_bolt_port="$(prompt_with_default "Neo4j Bolt host port" "7387")"
    neo4j_http_port="$(prompt_with_default "Neo4j HTTP host port" "7373")"
    neo4j_uri="$(prompt_with_default "Neo4j URI" "bolt://$neo4j_host:$neo4j_bolt_port")"
    neo4j_user="$(prompt_with_default "Neo4j user" "neo4j")"
    neo4j_password="$(prompt_secret_with_default "Neo4j password" "password")"
    thread_id="$(prompt_with_default "Default THREAD_ID" "create-agent-demo")"

    printf '\n'
    write_env_file \
        "$backend" \
        "$openai_base_url" \
        "$openai_api_key" \
        "$openai_model" \
        "$anthropic_api_key" \
        "$anthropic_model" \
        "$neo4j_host" \
        "$neo4j_bolt_port" \
        "$neo4j_http_port" \
        "$neo4j_uri" \
        "$neo4j_user" \
        "$neo4j_password" \
        "$thread_id" \
        "$huggingfacehub_api_token" \
        "$ministral_port" \
        "$ministral_replicas"

    printf '%s\n' "Wrote $output_file"
    printf '\n'
    printf '%s\n' "Next steps:"
    printf '%s\n' "  1. If using direnv: direnv allow"
    printf '%s\n' "  2. Or source manually:"
    printf '%s\n' "       set -a && . ./.env.local && set +a"
    printf '%s\n' "  3. Run a demo, for example:"
    printf '%s\n' "       cd packages/python && uv run python examples/simple_agent.py"
}

main "$@"
